      MODULE analy2_I   
      use parameters_biotr_C
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  19:41:09  11/16/01  
      SUBROUTINE analy2 (MCFG, KCFG, LIST) 
!      INTEGER NWD 
!      PARAMETER(NWD=128) 
      INTEGER, INTENT(OUT) :: MCFG 
      INTEGER, INTENT(OUT) :: KCFG 
      CHARACTER (LEN = 3), DIMENSION(*), INTENT(INOUT) :: LIST 
!VAST.../ELT/ ELTENS(OUT)
!VAST.../DBG/ IBUGM(IN)
!VAST.../INOUT/ IWRITE(IN), ISCW(IN), IUC(IN)
!VAST.../FO/ IWF(INOUT), NCLOS(INOUT), NOPEN(INOUT), MAXNFO(OUT)
!VAST.../NOR/ NCOM(OUT), NCLOSI(OUT), NCLOSF(OUT), NORBI(OUT)
!VAST.../NOR/ NORBF(OUT)
!VAST...Calls: FIND, DALLOC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE angmom_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:41:07  11/16/01  
      SUBROUTINE angmom (NEW, NZERO, IFIRST) 
      INTEGER, INTENT(IN) :: NEW 
      INTEGER :: NZERO 
!VAST...Dummy argument NZERO is not referenced in this routine.
      INTEGER :: IFIRST 
!VAST...Dummy argument IFIRST is not referenced in this routine.
!VAST.../FOUT/ IFLAG(OUT), NIJ(INOUT)
!VAST.../OVRLAP/ NORTH(IN), QIORTH(INOUT)
!VAST.../RED/ NC(OUT)
!VAST...Calls: NORTBPN, SETUP, ORTHOGG, LMATRIX, DALLOC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE cfgin2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:03:58  11/16/01  
      SUBROUTINE cfgin2 (MCFG, KCFG) 
      INTEGER NWD 
      PARAMETER(NWD=128) 
      INTEGER, INTENT(IN) :: MCFG 
      INTEGER, INTENT(IN) :: KCFG 
!VAST.../DBG/ IBUGM(IN)
!VAST.../INOUT/ IUC(IN)
!VAST.../NDIMS/ QNOC(INOUT), QNELCSH(INOUT), QNOCORB(INOUT)
!VAST.../NDIMS/ QJ1(INOUT), NCFG(OUT)
!VAST.../NON30/ QLJCOMP(INOUT), MAXORB(OUT)
!VAST.../NOR/ NCOM(IN), NCLOSI(IN), NCLOSF(IN), NORBI(IN)
!VAST.../NOR/ NORBF(IN)
!VAST...Calls: ANALY2, LVAL, GSTATE, CFGTST
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE cfgn1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:24:32  11/16/01  
      SUBROUTINE cfgn1 () 
      INTEGER NWD 
      PARAMETER(NWD=128) 
!VAST...Calls: CFGO1, ALLOC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE cfgo1_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  08:47:30  11/16/01
      SUBROUTINE cfgo1(NCLOSD)
      INTEGER, INTENT(OUT) :: NCLOSD
      END SUBROUTINE
      END INTERFACE
      END MODULE

      MODULE find_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      CHARACTER FUNCTION find (I, OF, EL) 
      INTEGER NWD 
      PARAMETER(NWD=128) 
      INTEGER, INTENT(IN) :: I 
      CHARACTER (LEN = 3), DIMENSION(NWD,2), INTENT(IN) :: OF 
      CHARACTER (LEN = 3), DIMENSION(NWD), INTENT(IN) :: EL 
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE gstate_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:27:20  11/16/01  
      SUBROUTINE gstate (NFIRST, NLAST) 
      INTEGER, INTENT(IN) :: NFIRST 
      INTEGER, INTENT(IN) :: NLAST 
!VAST...Calls: IUC, LVAL, NUMVAL
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ini_calc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE ini_calc (IEM, LAM, NPAIR, NTERMS, IFL) 
      INTEGER, INTENT(IN) :: IEM 
      INTEGER, INTENT(IN) :: LAM 
      INTEGER, INTENT(IN) :: NPAIR 
      INTEGER, INTENT(OUT) :: NTERMS 
      INTEGER, INTENT(INOUT) :: IFL 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ini_type_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE ini_type (IWRITE, IM, IFL, LAM, LAM2, VOK) 
      INTEGER, INTENT(IN) :: IWRITE 
      CHARACTER (LEN = 1), INTENT(INOUT) :: IM 
      INTEGER, INTENT(OUT) :: IFL 
      INTEGER, INTENT(IN) :: LAM 
      INTEGER, INTENT(OUT) :: LAM2 
      LOGICAL, INTENT(OUT) :: VOK 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ini_var_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE ini_var (LBUF, MXL, LMAX, NTESTB) 
      INTEGER, INTENT(OUT) :: LBUF 
      INTEGER, INTENT(OUT) :: MXL 
      INTEGER, DIMENSION(2), INTENT(IN) :: LMAX 
      INTEGER, INTENT(OUT) :: NTESTB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE inp_interact_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE inp_interact (NEW, NZERO, ISTRICT, ISTART, ISCW, NCFG) 
      INTEGER, INTENT(OUT) :: NEW 
      INTEGER, INTENT(OUT) :: NZERO 
      INTEGER, INTENT(OUT) :: ISTRICT 
      INTEGER, INTENT(OUT) :: ISTART 
      INTEGER, INTENT(IN) :: ISCW 
      INTEGER, INTENT(IN) :: NCFG 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE inp_print_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE inp_print (ISCW, IPRINT, TOL) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: ISCW 
!VAST...Dummy argument ISCW is not referenced in this routine.
      LOGICAL :: IPRINT 
!VAST...Dummy argument IPRINT is not referenced in this routine.
      REAL(DOUBLE) :: TOL 
!VAST...Dummy argument TOL is not referenced in this routine.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 


      MODULE lmatrix1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE lmatrix1 (IA) 
      INTEGER, INTENT(IN) :: IA 
!VAST.../CONSTS/ HALF(IN), EPS(IN)
!VAST.../MEDEFN/ LJ(INOUT), IJFUL(IN)
!VAST.../DIAGNL/ JA(INOUT), JB(INOUT)
!VAST.../TRK/ ID1(IN), IK1(IN)
!VAST...Calls: RECOUPLS0, HIBFF, SAVENON
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE lmatrix2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE lmatrix2 (IA, IB) 
      INTEGER, INTENT(IN) :: IA 
      INTEGER, INTENT(IN) :: IB 
!VAST.../CONSTS/ HALF(INOUT), EPS(IN)
!VAST.../MEDEFN/ IHSH(IN), LJ(INOUT), NOSH1(IN), IJFUL(INOUT)
!VAST.../DIAGNL/ JA(INOUT), JB(INOUT)
!VAST.../TRK/ BD1(INOUT), BD2(INOUT), BK1(INOUT), BK2(INOUT)
!VAST.../TRK/ ID1(INOUT), ID2(INOUT), IK1(INOUT), IK2(INOUT)
!VAST...Calls: RECOUPLS0, RECOUPLS2, HIBFF, A1A2LS, SAVENON
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE lmatrix_I   

      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE lmatrix 
!VAST.../MEDEFN/ IHSH(IN), LJ(IN), NOSH1(IN), NOSH2(IN), J1QN1(IN)
!VAST.../MEDEFN/ J1QN2(IN)
!VAST...Calls: LMATRIX2, LMATRIX1
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE mem_orth_I   

      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE mem_orth (NORBI, NORBF, NORTH, IBUGM, QIORTH) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NORBI 
      INTEGER, INTENT(IN) :: NORBF 
      INTEGER, INTENT(OUT) :: NORTH 
      INTEGER, INTENT(IN) :: IBUGM 
      INTEGER, POINTER :: QIORTH(:)
!VAST...Calls: ALLOC, ORTH
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE nonh1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  23:47:02  11/16/01  
      SUBROUTINE nonh1 (IK) 
      INTEGER NWD 
      PARAMETER(NWD=128) 
      INTEGER, INTENT(IN) :: IK 
!VAST.../FOUT/ LCOUNT(OUT), NREC(OUT), NIJ(OUT)
!VAST.../NLORB/ NQ1(INOUT), LQ1(INOUT), NQ2(INOUT), LQ2(INOUT)
!VAST...Calls: CFGN1, SETSUPRAS, ALLOC, ANGMOM, CN, IPACKN
!VAST...Calls: JAN, JBN, DALLOC, OUTLS, INTGRL1, INTPTR1
!VAST...Calls: CNN1, JANN1, JBNN1, INTGRL2, INTPTR2, CNN2
!VAST...Calls: JANN2, JBNN2, RSCHECK
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE nortbpn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  23:57:28  11/16/01  
      SUBROUTINE nortbpn (JA, JB) 
      INTEGER, INTENT(IN) :: JA 
      INTEGER, INTENT(IN) :: JB 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE open_lsjf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE open_lsjf (TTFILE, ISCW, ICI, IUJ, JFILE, TRFILE, IULSJ, NAME) 
      CHARACTER (LEN = 64), INTENT(IN) :: TTFILE 
!VAST...Dummy argument ISCW is not referenced in this routine.
      INTEGER, INTENT(OUT) :: ICI 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(IN) :: JFILE 
      CHARACTER (LEN = 64), INTENT(OUT) :: TRFILE 
      INTEGER, INTENT(IN) :: IULSJ 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(IN) :: NAME 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE orth_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  00:00:10  11/17/01  
      SUBROUTINE orth 
!VAST.../NOR/ NCOM(IN), NORBI(IN), NORBF(IN)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE orthogg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE orthogg (LET) 
      INTEGER, INTENT(OUT) :: LET 
!VAST.../INFORM/ IWRITE(IN)
!VAST.../MEDEFN/ IHSH(IN), LJ(IN), NOSH1(IN), NOSH2(IN)
!VAST.../SIGNF/ SIGNFA(OUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE outls_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  00:07:05  11/17/01  
      SUBROUTINE outls (INTGRL, NINT, INTPTR, CNN, NCOEF, JANN, JBNN) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER LSTACK 
      PARAMETER (LSTACK = 128) 
      INTEGER, DIMENSION(*), INTENT(OUT) :: INTGRL 
      INTEGER, INTENT(OUT) :: NINT 
      INTEGER, DIMENSION(*), INTENT(OUT) :: INTPTR 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: CNN 
      INTEGER, INTENT(OUT) :: NCOEF 
      INTEGER, DIMENSION(*), INTENT(OUT) :: JANN 
      INTEGER, DIMENSION(*), INTENT(OUT) :: JBNN 
!VAST.../FOUT/ LCOUNT(IN), NREC(IN)
!VAST.../INFORM/ ISC(IN), ISCW(IN)
!VAST...Calls: IPACKN, QSORT, EXIT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE rasin_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  00:08:29  11/17/01  
      SUBROUTINE rasin 
!VAST.../RAS/ NINAC(IN), NRAS2(IN), NL(INOUT), ELRAS(INOUT)
!VAST.../RAS/ LMAX(IN)
!VAST.../FO/ MAXNFO(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE rscheck_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE rscheck (NQ, LQ, LMX, MX) 
      INTEGER NWD 
      PARAMETER (NWD = 128) 
      INTEGER, DIMENSION(NWD), INTENT(IN) :: NQ 
      INTEGER, DIMENSION(NWD), INTENT(IN) :: LQ 
      INTEGER, INTENT(IN) :: LMX 
      INTEGER, INTENT(IN) :: MX 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE savels_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  00:10:17  11/17/01  
      SUBROUTINE savels (ICASE, C, K, I1, I2, I3, I4, JA, JB, IPTR) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: ICASE 
!VAST...Dummy argument ICASE is not referenced in this routine.
      REAL(DOUBLE), INTENT(IN) :: C 
      INTEGER, INTENT(IN) :: K 
      INTEGER :: I1 
!VAST...Dummy argument I1 is not referenced in this routine.
      INTEGER, INTENT(IN) :: I2 
      INTEGER :: I3 
!VAST...Dummy argument I3 is not referenced in this routine.
      INTEGER, INTENT(IN) :: I4 
      INTEGER, INTENT(IN) :: JA 
      INTEGER, INTENT(IN) :: JB 
      INTEGER :: IPTR 
!VAST...Dummy argument IPTR is not referenced in this routine.
!VAST...Calls: ISC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE set_debug_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE set_debug (IBUG1, IBUG2, IBUG3, IBUGM, NBUG6) 
      integer, INTENT(OUT) :: IBUG1 
      integer, INTENT(OUT) :: IBUG2 
      integer, INTENT(OUT) :: IBUG3 
      integer, INTENT(OUT) :: IBUGM 
      integer, INTENT(OUT) :: NBUG6 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE set_ncf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE set_ncf (LCFG, NCFG, MCFG, KCFG, NCF) 
      integer, INTENT(OUT) :: LCFG 
      integer, INTENT(IN) :: NCFG 
      integer, INTENT(IN) :: MCFG 
      integer, INTENT(IN) :: KCFG 
      integer, DIMENSION(2), INTENT(OUT) :: NCF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE set_unit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE set_unit (IULS, IULSJ) 
!VAST...Dummy argument IUT is not referenced in this routine.
      INTEGER, INTENT(OUT) :: IULS 
      INTEGER, INTENT(OUT) :: IULSJ 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE setsupras_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  00:14:13  11/17/01  
      SUBROUTINE setsupras (IK,NCLOSD) 
      INTEGER NWD 
      PARAMETER(NWD=128) 
      INTEGER, INTENT(IN) :: IK,NCLOSD 
!VAST.../RAS/ NINAC(INOUT), NRAS2(INOUT), LMAX(OUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE setupb_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:13:35  11/17/01  
      SUBROUTINE setupb (JA, JB, LET) 
      INTEGER, INTENT(IN) :: JA 
      INTEGER, INTENT(IN) :: JB 
      INTEGER, INTENT(OUT) :: LET 
!VAST...Calls: SETUPM
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE setupm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:13:59  11/17/01  
      SUBROUTINE setupm (ISH, J1, J2, JA, JB, NA, NB) 
      INTEGER, INTENT(IN) :: ISH 
      INTEGER, INTENT(IN) :: J1 
      INTEGER, INTENT(IN) :: J2 
      INTEGER, INTENT(IN) :: JA 
      INTEGER, INTENT(IN) :: JB 
      INTEGER, INTENT(IN) :: NA 
      INTEGER, INTENT(IN) :: NB 
!VAST.../RED/ INDL(IN), INDR(IN), NCI1(IN), KPL(OUT), KPR(OUT)
!VAST.../RED/ NC(IN)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE write_hdr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE write_hdr (IWRITE) 
      INTEGER, INTENT(IN) :: IWRITE 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
