      MODULE inp_type_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01
      SUBROUTINE inp_type (ISCW,IWRITE,IREAD,IFL,LAM,LAM2,VOK,IM)
      INTEGER , INTENT(IN) :: ISCW
      INTEGER , INTENT(IN) :: IWRITE
      INTEGER , INTENT(IN) :: IREAD
      INTEGER , INTENT(OUT) :: IFL
      INTEGER , INTENT(OUT) :: LAM
      INTEGER , INTENT(OUT) :: LAM2
      LOGICAL , INTENT(OUT) :: VOK
      CHARACTER, INTENT(OUT) :: IM
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE

      MODULE initm2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:58:56  11/18/01  
      SUBROUTINE initm2 (IPROB) 
      INTEGER NOD 
      PARAMETER(NOD=220) 
      INTEGER NELEMENT 
      PARAMETER(NELEMENT=50) 
      INTEGER, INTENT(IN) :: IPROB 
!VAST.../INOUT/ IREAD(IN), ISCW(IN)
!VAST.../PARAM/ H(IN), RHO(OUT), Z(IN), NO(IN), RMASS(OUT)
!VAST.../RADIAL/ R(INOUT), RR(OUT), R2(OUT)
!VAST.../RYDBERG/ RYDBRG(OUT), ZMU(OUT)
!VAST.../COR/ FZE(OUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE rdegvc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:09:36  11/18/01  
      SUBROUTINE rdegvc 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE ifnmnx_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:59:28  11/18/01  
      INTEGER FUNCTION ifnmnx (IVEC, NEL, IMXMN) 
      INTEGER, DIMENSION(NEL), INTENT(IN) :: IVEC 
      INTEGER, INTENT(IN) :: NEL 
      INTEGER, INTENT(IN) :: IMXMN 
!...This routine performs I/O.
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE polint_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:35  11/20/01  
      SUBROUTINE polint (XA, YA, N, X, Y, DY) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER NMAX 
      PARAMETER (NMAX = 10) 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: XA 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: YA 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: X 
      REAL(DOUBLE), INTENT(OUT) :: Y 
      REAL(DOUBLE), INTENT(OUT) :: DY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE inp_atom_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:27:44  11/14/01  
      SUBROUTINE inp_atom (NAME,CFILE,WFILE,LFILE,JFILE,LINTF,TFILE,TTFILE) 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(IN) :: NAME 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: CFILE 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: WFILE 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: LFILE 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: JFILE 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: LINTF 
      CHARACTER (LEN = 24), DIMENSION(2), INTENT(OUT) :: TFILE 
      CHARACTER (LEN = 64), INTENT(OUT) :: TTFILE
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ielsum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:00:23  11/18/01  
      INTEGER FUNCTION ielsum (IVEC, NELMNT) 
      INTEGER, DIMENSION(*), INTENT(IN) :: IVEC 
      INTEGER, INTENT(IN) :: NELMNT 
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE grad2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:26:02  11/20/01  
      REAL(KIND(0.0D0)) FUNCTION grad2 (I, J) 
      INTEGER NOD 
      PARAMETER(NOD=220) 
      INTEGER NWD 
      PARAMETER(NWD=128) 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
!VAST...Calls: QUADR
!...This routine performs I/O.
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE nortbp_I   

      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:25:16  11/20/01  
      SUBROUTINE nortbp (JA, JB) 
      INTEGER, INTENT(IN) :: JA 
      INTEGER, INTENT(IN) :: JB 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE nontrans_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:27:41  11/20/01  
      SUBROUTINE nontrans (KA, KB, CL, CV) 
      USE vast_kind_param,ONLY: DOUBLE1=>DOUBLE 
      INTEGER :: KA 
      INTEGER :: KB 
      REAL(DOUBLE1), INTENT(OUT) :: CL 
      REAL(DOUBLE1), INTENT(OUT) :: CV 
!VAST.../SAVECOM/ LRHO(OUT), LSIG(OUT), CL2(OUT), CV2(OUT)
!VAST...Calls: TRANSITION, ITTK, ONEPARTICLE2, ONEPARTICLE1
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE fline_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:29:54  11/20/01  
      REAL(KIND(0.0D0)) FUNCTION fline (K) 
      INTEGER, INTENT(IN) :: K 
!VAST.../LSJ/ LL1(OUT), LL2(OUT), IS1(OUT), IS2(OUT)
!VAST...Calls: SIXJ, NINELS
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE setup_oc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  13:42:29  11/20/01  
      SUBROUTINE setup_oc (JA, JB, LET) 
      INTEGER :: JA 
      INTEGER :: JB 
      INTEGER :: LET 
!VAST...Calls: SETUPM
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE calcul_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  11:53:59  11/20/01  
      SUBROUTINE calcul (NPAIR) 
      INTEGER, INTENT(INOUT) :: NPAIR 
!VAST...Calls: NORTBP, SETUP, ITTK, NONTRANS, FLINE
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE trp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:26:07  11/20/01  
      REAL(KIND(0.0D0)) FUNCTION trp (END, LAM, DD) 
      USE vast_kind_param,ONLY: DOUBLE1=>DOUBLE 
      CHARACTER (LEN = 1), INTENT(IN) :: END 
      INTEGER, INTENT(IN) :: LAM 
      REAL(DOUBLE1), INTENT(IN) :: DD 
!...This routine performs I/O.
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE transition_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  14:28:09  11/20/01  
      SUBROUTINE transition (L1, L2, I, A) 
      USE vast_kind_param,ONLY: DOUBLE1=>DOUBLE 
      INTEGER :: L1 
!VAST...Dummy argument L1 is not referenced in this routine.
      INTEGER :: L2 
!VAST...Dummy argument L2 is not referenced in this routine.
      INTEGER, INTENT(OUT) :: I 
      REAL(DOUBLE1), INTENT(OUT) :: A 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE gets_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:01:51  11/18/01  
      SUBROUTINE gets (S, NSHLI, NSHLF) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NSHLI,NSHLF), INTENT(OUT) :: S 
      INTEGER, INTENT(IN) :: NSHLI 
      INTEGER, INTENT(IN) :: NSHLF 
!VAST...Calls: QUADR, WRTMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE scalve_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:09:24  11/18/01  
      SUBROUTINE scalve (VECTOR, FACTOR, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: VECTOR 
      REAL(DOUBLE), INTENT(IN) :: FACTOR 
      INTEGER, INTENT(IN) :: NDIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE copvec_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:02:41  11/18/01  
      SUBROUTINE copvec (FROM, TO, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(IN) :: FROM 
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(OUT) :: TO 
      INTEGER, INTENT(IN) :: NDIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE invmat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:04:40  11/18/01  
      SUBROUTINE invmat (A, B, MATDIM, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(MATDIM,MATDIM), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(MATDIM,MATDIM) :: B 
      INTEGER, INTENT(IN) :: MATDIM 
      INTEGER, INTENT(IN) :: NDIM 
!VAST...Calls: BNDINV, WRTMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ulla_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:06:53  11/18/01  
      SUBROUTINE ulla (A, U, L, NDIM, SCR) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(OUT) :: U 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(OUT) :: L 
      INTEGER, INTENT(IN) :: NDIM 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: SCR 
!VAST...Calls: LULU, SETVEC, WRTMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE trpmat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:08:09  11/18/01  
      SUBROUTINE trpmat (XIN, NROW, NCOL, XOUT) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NROW,NCOL), INTENT(IN) :: XIN 
      INTEGER, INTENT(IN) :: NROW 
      INTEGER, INTENT(IN) :: NCOL 
      REAL(DOUBLE), DIMENSION(NCOL,NROW), INTENT(OUT) :: XOUT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE matml4_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:08:48  11/18/01  
      SUBROUTINE matml4 (C, A, B, NCROW, NCCOL, NAROW, NACOL, NBROW, NBCOL&
         , ITRNSP) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCROW,NCCOL), INTENT(INOUT) :: C 
      REAL(DOUBLE), DIMENSION(NAROW,NACOL), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(NBROW,NBCOL), INTENT(IN) :: B 
      INTEGER, INTENT(IN) :: NCROW 
      INTEGER, INTENT(IN) :: NCCOL 
      INTEGER, INTENT(IN) :: NAROW 
      INTEGER, INTENT(IN) :: NACOL 
      INTEGER, INTENT(IN) :: NBROW 
      INTEGER, INTENT(IN) :: NBCOL 
      INTEGER, INTENT(IN) :: ITRNSP 
!VAST...Calls: WRTMAT, SETVEC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE setvec_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:10:06  11/18/01  
      SUBROUTINE setvec (VECTOR, VALUE, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: VECTOR 
      REAL(DOUBLE), INTENT(IN) :: VALUE 
      INTEGER, INTENT(IN) :: NDIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE pamtmt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:10:54  11/18/01  
      SUBROUTINE pamtmt (X, T, WORK, NORB) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NORB,NORB) :: X 
      REAL(DOUBLE), DIMENSION(NORB,NORB), INTENT(OUT) :: T 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: WORK 
      INTEGER, INTENT(IN) :: NORB 
!VAST...Calls: LULU, SETVEC, WRTMAT, INVMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE vecsum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:37:32  11/18/01  
      SUBROUTINE vecsum (C, A, B, FACA, FACB, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(1), INTENT(OUT) :: C 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: B 
      REAL(DOUBLE), INTENT(IN) :: FACA 
      REAL(DOUBLE), INTENT(IN) :: FACB 
      INTEGER, INTENT(IN) :: NDIM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE wrtmat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:03:39  11/18/01  
      SUBROUTINE wrtmat (A_, NROW, NCOL, NMROW, NMCOL) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NMROW,NMCOL), INTENT(IN) :: A_ 
      INTEGER, INTENT(IN) :: NROW 
      INTEGER, INTENT(IN) :: NCOL 
      INTEGER, INTENT(IN) :: NMROW 
      INTEGER, INTENT(IN) :: NMCOL 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE bndinv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:05:05  11/18/01  
      SUBROUTINE bndinv (A, EL, N, DETERM, EPSIL, ITEST, NSIZE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NSIZE,1), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(NSIZE,1), INTENT(INOUT) :: EL 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(OUT) :: DETERM 
      REAL(DOUBLE), INTENT(IN) :: EPSIL 
      INTEGER, INTENT(OUT) :: ITEST 
      INTEGER, INTENT(IN) :: NSIZE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE lulu_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:07:39  11/18/01  
      SUBROUTINE lulu (A, L, U, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: L 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: U 
      INTEGER, INTENT(IN) :: NDIM 
!VAST...Calls: INPROD, PRSYM
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE inprod_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:34:07  11/18/01  
      REAL(KIND(0.0D0)) FUNCTION inprod (A, B, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(2), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(2), INTENT(IN) :: B 
      INTEGER, INTENT(IN) :: NDIM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE prsym_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:35:29  11/18/01  
      SUBROUTINE prsym (A, MATDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: A 
      INTEGER, INTENT(IN) :: MATDIM 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE ti1tv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:57:01  11/18/01  
      SUBROUTINE ti1tv (CIIN, NCSF, NCIV, I, L, T, NSHL, JLEI, LBUF, LU, CIOUT&
         , BUF, IBUF, NTESTG) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(IN) :: CIIN 
      INTEGER, INTENT(IN) :: NCSF 
      INTEGER, INTENT(IN) :: NCIV 
      INTEGER :: I 
      INTEGER :: L 
      REAL(DOUBLE), DIMENSION(NSHL), INTENT(IN) :: T 
      INTEGER, INTENT(IN) :: NSHL 
      INTEGER :: JLEI 
      INTEGER, INTENT(IN) :: LBUF 
      INTEGER :: LU 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(INOUT) :: CIOUT 
      REAL(DOUBLE), DIMENSION(LBUF), INTENT(IN) :: BUF 
      INTEGER, DIMENSION(4,LBUF), INTENT(IN) :: IBUF 
      INTEGER, INTENT(IN) :: NTESTG 
!VAST...Calls: SETVEC, GTRAC1, WRTMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tiini_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  17:57:07  11/18/01  
      SUBROUTINE tiini (CIIN, NCSF, NCIV, I, L, CONST, LBUF, LU, CIOUT, BUF&
         , IBUF, NTESTG) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(IN) :: CIIN 
      INTEGER, INTENT(IN) :: NCSF 
      INTEGER, INTENT(IN) :: NCIV 
      INTEGER :: I 
      INTEGER :: L 
      REAL(DOUBLE), INTENT(IN) :: CONST 
      INTEGER, INTENT(IN) :: LBUF 
      INTEGER :: LU 
      REAL(DOUBLE), DIMENSION(NCSF,NCIV), INTENT(INOUT) :: CIOUT 
      REAL(DOUBLE), DIMENSION(LBUF), INTENT(IN) :: BUF 
      INTEGER, DIMENSION(4,LBUF), INTENT(IN) :: IBUF 
      INTEGER, INTENT(IN) :: NTESTG 
!VAST...Calls: SETVEC, GTRAC1, WRTMAT
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE gtrac1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:39:43  11/18/01  
      SUBROUTINE gtrac1 (I, L, IFIRST, NFOUND, BUF, IBUF, LBUF, JLEI, LU&
         , NTESTG) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: I 
      INTEGER :: L 
      INTEGER :: IFIRST 
      INTEGER :: NFOUND 
      REAL(DOUBLE) :: BUF 
      INTEGER :: IBUF 
      INTEGER :: LBUF 
      INTEGER :: JLEI 
      INTEGER, INTENT(IN) :: LU 
      INTEGER :: NTESTG 
!VAST...Calls: GTRACXVN
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE gtracxvn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:23:09  11/20/01  
      SUBROUTINE gtracxvn (I, LINP, IFIRST, NFOUND, BUF, IBUF, LBUF, JLEI, IORF&
         , NTESTG) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER NWD 
      PARAMETER (NWD = 128) 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: LINP 
      INTEGER, INTENT(IN) :: IFIRST 
      INTEGER, INTENT(OUT) :: NFOUND 
      REAL(DOUBLE), DIMENSION(LBUF), INTENT(INOUT) :: BUF 
      INTEGER, DIMENSION(4,LBUF), INTENT(INOUT) :: IBUF 
      INTEGER, INTENT(IN) :: LBUF 
      INTEGER, INTENT(IN) :: JLEI 
      INTEGER, INTENT(IN) :: IORF 
      INTEGER, INTENT(IN) :: NTESTG 
!VAST.../GTRACLOC/ LISTCUR(INOUT), IELMCUR(INOUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
