      MODULE acurat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION acurat (C) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: C 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE alloc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE alloc (PTR, NMLOCS, LENGTH) 
      REAL, INTENT(INOUT) :: PTR 
      INTEGER, INTENT(IN) :: NMLOCS 
      INTEGER, INTENT(IN) :: LENGTH 
!VAST...Calls: MALLOC
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE bisect_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE bisect (N, EPS1, D, E, E2, LB, UB, MM, M, W, IND, IERR, RV4&
         , RV5) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(INOUT) :: EPS1 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: D 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: E 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E2 
      REAL(DOUBLE), INTENT(INOUT) :: LB 
      REAL(DOUBLE), INTENT(INOUT) :: UB 
      INTEGER, INTENT(IN) :: MM 
      INTEGER, INTENT(INOUT) :: M 
      REAL(DOUBLE), DIMENSION(MM), INTENT(INOUT) :: W 
      INTEGER, DIMENSION(MM), INTENT(INOUT) :: IND 
      INTEGER, INTENT(OUT) :: IERR 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV4 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV5 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE bwint_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE bwint (LC, LO) 
      INTEGER, INTENT(IN) :: LC 
      INTEGER, INTENT(IN) :: LO 
!VAST.../BLUME/ COEFN2(OUT), COEFNK(OUT), COEFVK(OUT)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE ca_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION ca (L, K) 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: K 
!VAST.../EAV/ CCA(IN)
!VAST...Calls: RME
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE cb_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION cb (L, LP, K) 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: LP 
      INTEGER, INTENT(IN) :: K 
!VAST.../EAV/ CCB(IN)
!VAST...Calls: RME
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE dalloc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dalloc (PTR, LENGTH) 
      REAL :: PTR 
      INTEGER :: LENGTH 
!VAST...Dummy argument LENGTH is not referenced in this routine.
!VAST...Calls: FREE
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dasum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION dasum (N, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      INTEGER, INTENT(IN) :: INCX 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE daxpy_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE daxpy (N, DA, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: DA 
      real(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(1), INTENT(INOUT) :: DY 
      integer, INTENT(IN) :: INCY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dcopy_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dcopy (N, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(1), INTENT(OUT) :: DY 
      integer, INTENT(IN) :: INCY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE ddot_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION ddot (N, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(1), INTENT(IN) :: DY 
      integer, INTENT(IN) :: INCY 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE dfill_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dfill (N, ALPHA, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(1), INTENT(OUT) :: DX 
      integer, INTENT(IN) :: INCX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgbco_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgbco (ABD, LDA, N, ML, MU, IPVT, RCOND, Z) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: ML 
      integer, INTENT(IN) :: MU 
      integer, DIMENSION(1), INTENT(IN) :: IPVT 
      real(DOUBLE), INTENT(OUT) :: RCOND 
      real(DOUBLE), DIMENSION(1), INTENT(INOUT) :: Z 
!VAST...Calls: DDOT, DASUM, DGBFA, DSCAL, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgbdi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgbdi (ABD, LDA, N, ML, MU, IPVT, DET) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: ML 
      INTEGER, INTENT(IN) :: MU 
      INTEGER, DIMENSION(1), INTENT(IN) :: IPVT 
      REAL(DOUBLE), DIMENSION(2), INTENT(INOUT) :: DET 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgbfa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgbfa (ABD, LDA, N, ML, MU, IPVT, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(INOUT) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: ML 
      INTEGER, INTENT(IN) :: MU 
      INTEGER, DIMENSION(1), INTENT(INOUT) :: IPVT 
      INTEGER, INTENT(OUT) :: INFO 
!VAST...Calls: IDAMAX, DSCAL, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgbsl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgbsl (ABD, LDA, N, ML, MU, IPVT, B, JOB) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: ML 
      INTEGER, INTENT(IN) :: MU 
      INTEGER, DIMENSION(1), INTENT(IN) :: IPVT 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: B 
      INTEGER, INTENT(IN) :: JOB 
!VAST...Calls: DDOT, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgeco_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgeco (A, LDA, N, IPVT, RCOND, Z) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: A 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, DIMENSION(1), INTENT(IN) :: IPVT 
      REAL(DOUBLE), INTENT(OUT) :: RCOND 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: Z 
!VAST...Calls: DDOT, DASUM, DGEFA, DSCAL, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgedi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgedi (A, LDA, N, IPVT, DET, WORK, JOB) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, DIMENSION(1), INTENT(IN) :: IPVT 
      REAL(DOUBLE), DIMENSION(2), INTENT(INOUT) :: DET 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: WORK 
      INTEGER, INTENT(IN) :: JOB 
!VAST...Calls: DSCAL, DAXPY, DSWAP
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgefa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgefa (A, LDA, N, IPVT, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, DIMENSION(1), INTENT(OUT) :: IPVT 
      INTEGER, INTENT(OUT) :: INFO 
!VAST...Calls: IDAMAX, DSCAL, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgemv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      CHARACTER (LEN = 1) :: TRANS 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: ALPHA 
      REAL(DOUBLE), DIMENSION(LDA,*), INTENT(IN) :: A 
      INTEGER, INTENT(IN) :: LDA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      INTEGER, INTENT(IN) :: INCX 
      REAL(DOUBLE), INTENT(IN) :: BETA 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: Y 
      INTEGER, INTENT(IN) :: INCY 
!VAST...Calls: LSAME, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dger_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: ALPHA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      INTEGER, INTENT(IN) :: INCX 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: Y 
      INTEGER, INTENT(IN) :: INCY 
      REAL(DOUBLE), DIMENSION(LDA,*), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: LDA 
!VAST...Calls: XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgesl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dgesl (A, LDA, N, IPVT, B, JOB) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: A 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, DIMENSION(1), INTENT(IN) :: IPVT 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: B 
      INTEGER, INTENT(IN) :: JOB 
!VAST...Calls: DDOT, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dnrm2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION dnrm2 (N, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      INTEGER, INTENT(IN) :: INCX 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE dpbco_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dpbco (ABD, LDA, N, M, RCOND, Z, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: M 
      real(DOUBLE), INTENT(OUT) :: RCOND 
      real(DOUBLE), DIMENSION(1), INTENT(INOUT) :: Z 
      integer, INTENT(IN) :: INFO 
!VAST...Calls: DDOT, DASUM, DPBFA, DSCAL, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dpbdi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dpbdi (ABD, LDA, N, M, DET) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(2), INTENT(INOUT) :: DET 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dpbfa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dpbfa (ABD, LDA, N, M, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(INOUT) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(OUT) :: INFO 
!VAST...Calls: DDOT
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dpbsl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dpbsl (ABD, LDA, N, M, B) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(LDA,1), INTENT(IN) :: ABD 
      INTEGER, INTENT(IN) :: LDA 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: B 
!VAST...Calls: DDOT, DAXPY
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dscal_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dscal (N, DA, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: DA 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: DX 
      INTEGER, INTENT(IN) :: INCX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dspevx_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dspevx (JOBZ, RANGE, UPLO, N, AP, VL, VU, IL, IU, ABSTOL, M, W&
         , Z, LDZ, WORK, IWORK, IFAIL, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      character (LEN = 1) :: JOBZ 
      character (LEN = 1) :: RANGE 
      character (LEN = 1) :: UPLO 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: AP 
      real(DOUBLE), INTENT(IN) :: VL 
      real(DOUBLE), INTENT(IN) :: VU 
      integer, INTENT(IN) :: IL 
      integer, INTENT(IN) :: IU 
      real(DOUBLE), INTENT(IN) :: ABSTOL 
      integer, INTENT(OUT) :: M 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: W 
      real(DOUBLE), DIMENSION(LDZ,*), INTENT(OUT) :: Z 
      integer, INTENT(IN) :: LDZ 
      real(DOUBLE), DIMENSION(*) :: WORK 
      integer, DIMENSION(*), INTENT(INOUT) :: IWORK 
      integer, DIMENSION(*), INTENT(INOUT) :: IFAIL 
      integer, INTENT(OUT) :: INFO 
!VAST...Calls: LSAME, DLAMCH, DLANSP, DCOPY, DOPGTR, DOPMTR
!VAST...Calls: DSCAL, DSPTRD, DSTEBZ, DSTEIN, DSTEQR, DSTERF
!VAST...Calls: DSWAP, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dspmv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dspmv (UPLO, N, ALPHA, AP, X, INCX, BETA, Y, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      CHARACTER (LEN = 1) :: UPLO 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: ALPHA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: AP 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      INTEGER, INTENT(IN) :: INCX 
      REAL(DOUBLE), INTENT(IN) :: BETA 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: Y 
      INTEGER, INTENT(IN) :: INCY 
!VAST...Calls: LSAME, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dspr2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dspr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, AP) 
      USE vast_kind_param,ONLY: DOUBLE 
      CHARACTER (LEN = 1) :: UPLO 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: ALPHA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      INTEGER, INTENT(IN) :: INCX 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: Y 
      INTEGER, INTENT(IN) :: INCY 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: AP 
!VAST...Calls: LSAME, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dswap_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE dswap (N, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: DX 
      INTEGER, INTENT(IN) :: INCX 
      REAL(DOUBLE), DIMENSION(1), INTENT(INOUT) :: DY 
      INTEGER, INTENT(IN) :: INCY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE eptr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE eptr (EL, ELSYMB, IEL, J1) 
      character (LEN = 3), DIMENSION(*), INTENT(IN) :: EL 
      character (LEN = 3), INTENT(IN) :: ELSYMB 
      integer, INTENT(OUT) :: IEL 
      integer, INTENT(OUT) :: J1 
!VAST.../PARAM/ NWF(IN)
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE factrl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE factrl (NFACT) 
      INTEGER, INTENT(IN) :: NFACT 
!VAST.../FACT/ GAM(INOUT)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE fk_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION fk (I, J, K, REL) 
      INTEGER :: I 
      INTEGER :: J 
      INTEGER :: K 
      LOGICAL :: REL 
!VAST.../PARAM/ MSOO(IN), D1(IN), D2(IN), RMASS(IN)
!VAST...Calls: YKF, QUADS
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE gk_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION gk (I, J, K, REL) 
      INTEGER :: I 
      INTEGER :: J 
      INTEGER, INTENT(IN) :: K 
      LOGICAL :: REL 
!VAST.../PARAM/ Z(IN), MASS(IN), D1(IN), D2(IN), RMASS(IN)
!VAST...Calls: YKF, QUADS, GRAD, QUADR
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE gracah_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE gracah (I, J, K, L, M, N, RAC) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(OUT) :: RAC 
!VAST.../FACT/ GAM(IN)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE hnorm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION hnorm (N, L, ZZ) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: L 
      REAL(DOUBLE), INTENT(IN) :: ZZ 
!VAST.../PARAM/ D1(IN)
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE hwf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION hwf (N, L, ZZ, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: L 
      REAL(DOUBLE), INTENT(IN) :: ZZ 
      REAL(DOUBLE), INTENT(IN) :: R 
!VAST.../PARAM/ D0(IN), D1(IN), D2(IN)
!...This routine performs I/O.
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE idamax_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      INTEGER FUNCTION idamax (N, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(1), INTENT(IN) :: DX 
      INTEGER, INTENT(IN) :: INCX 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE ifill_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE ifill (N, IALPHA, IX, INCX) 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: IALPHA 
      integer, DIMENSION(1), INTENT(OUT) :: IX 
      integer, INTENT(IN) :: INCX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE imtqlv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE imtqlv (N, D, E, E2, W, IND, IERR, RV1) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: D 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: E 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E2 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: W 
      integer, DIMENSION(N), INTENT(INOUT) :: IND 
      integer, INTENT(OUT) :: IERR 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV1 
!VAST...Calls: PYTHAG
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE inita_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE inita 
!VAST.../EAV/ CCA(OUT), CCB(OUT)
!VAST...Calls: FACTRL
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE initr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE initr 
!VAST.../PARAM/ H(OUT), H1(OUT), H3(OUT), CH(OUT), EH(OUT)
!VAST.../PARAM/ RHO(OUT), NO(OUT), ND(OUT), D0(OUT), D1(OUT)
!VAST.../PARAM/ D2(OUT), D3(OUT), D4(OUT), D5(OUT), D6(OUT)
!VAST.../PARAM/ D8(OUT), D10(OUT), D12(OUT), D16(OUT), D30(OUT)
!VAST.../PARAM/ FINE(OUT)
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE intact_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE intact (L, LP, IEQUIV) 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: LP 
      INTEGER, INTENT(IN) :: IEQUIV 
!VAST.../ENAV/ NINTS(OUT), KVALUE(OUT), COEFCT(OUT)
!VAST.../EAV/ CCA(IN), CCB(IN)
!VAST...Calls: RME
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE lineqn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE lineqn (NDIM, N, A, B) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NDIM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(NDIM,*), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: B 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

      MODULE lval_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      INTEGER FUNCTION lval (SYMBOL) 
      CHARACTER (LEN = 1), INTENT(IN) :: SYMBOL 
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE pack_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE pack (M, EL, Q, COUPLE, STR) 
      INTEGER, INTENT(IN) :: M 
      CHARACTER (LEN = 3), DIMENSION(*), INTENT(IN) :: EL 
      INTEGER, DIMENSION(*), INTENT(IN) :: Q 
      CHARACTER (LEN = 3), DIMENSION(*), INTENT(IN) :: COUPLE 
      CHARACTER (LEN = 64), INTENT(OUT) :: STR 
!VAST...Calls: LVAL
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE pythag_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION pythag (A, B) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: A 
      REAL(DOUBLE), INTENT(IN) :: B 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE qsort_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE qsort (N, KEY, PT, STACK, NSTACK, IERR) 
      integer, INTENT(IN) :: N 
      integer, DIMENSION(*), INTENT(IN) :: KEY 
      integer, DIMENSION(*), INTENT(INOUT) :: PT 
      integer, DIMENSION(*), INTENT(INOUT) :: STACK 
      integer, INTENT(IN) :: NSTACK 
      integer, INTENT(OUT) :: IERR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE reform_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE reform (STR1, STR2) 
      character (LEN = 40), INTENT(IN) :: STR1 
      character (LEN = 40), INTENT(OUT) :: STR2 
!...This routine performs I/O.
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE rme_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION rme (L, LP, K) 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: LP 
      INTEGER, INTENT(IN) :: K 
!VAST.../FACT/ GAM(IN)
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE sn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION sn (I, J, II, JJ, K) 
      INTEGER :: I 
      INTEGER :: J 
      INTEGER :: II 
      INTEGER :: JJ 
      INTEGER :: K 
!VAST.../PARAM/ FINE(IN)
!VAST...Calls: ZK, QUADS
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE symmeq_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE symmeq (NDIM, N, A, X) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NDIM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(NDIM,*), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: X 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE symmsl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE symmsl (NDIM, N, A, X) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NDIM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(NDIM,*), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: X 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tinvit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE tinvit (NM, N, D, E, E2, M, W, IND, Z, IERR, RV1, RV2, RV3&
         , RV4, RV6) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: D 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: E 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: E2 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(M), INTENT(IN) :: W 
      INTEGER, DIMENSION(M), INTENT(IN) :: IND 
      REAL(DOUBLE), DIMENSION(NM,M), INTENT(INOUT) :: Z 
      INTEGER, INTENT(OUT) :: IERR 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV1 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV2 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV3 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV4 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV6 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tql2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE tql2 (NM, N, D, E, Z, IERR) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: D 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E 
      REAL(DOUBLE), DIMENSION(NM,N), INTENT(INOUT) :: Z 
      INTEGER, INTENT(OUT) :: IERR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE trbak1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE trbak1 (NM, N, A, E, M, Z) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(NM,N), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: E 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(NM,M), INTENT(INOUT) :: Z 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE trbak3_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE trbak3 (NM, N, NV, A, M, Z) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NM 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NV 
      REAL(DOUBLE), DIMENSION(NV), INTENT(IN) :: A 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(NM,M), INTENT(INOUT) :: Z 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tred1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE tred1 (NM, N, A, D, E, E2) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NM 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(NM,N), INTENT(INOUT) :: A 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: D 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E 
      real(DOUBLE), DIMENSION(N), INTENT(OUT) :: E2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tred2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE tred2 (NM, N, A, D, E, Z) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NM 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(NM,N), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: D 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E 
      REAL(DOUBLE), DIMENSION(NM,N), INTENT(INOUT) :: Z 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE tred3_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      SUBROUTINE tred3 (N, NV, A, D, E, E2) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NV 
      REAL(DOUBLE), DIMENSION(NV), INTENT(INOUT) :: A 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: D 
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E 
      REAL(DOUBLE), DIMENSION(N), INTENT(OUT) :: E2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE uk_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION uk (I, J, II, JJ, K) 
      integer :: I 
      integer :: J 
      integer :: II 
      integer :: JJ 
      integer, INTENT(IN) :: K 
!VAST.../PARAM/ FINE(IN)
!VAST...Calls: DZK, QUADS, YKK
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE vk_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION vk (I, J, II, JJ, K) 
      INTEGER :: I 
      INTEGER :: J 
      INTEGER :: II 
      INTEGER :: JJ 
      INTEGER :: K 
!VAST.../PARAM/ FINE(IN)
!VAST...Calls: DYK, QUADS
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE zcb_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  21:49:59  11/14/01  
      REAL(KIND(0.0D0)) FUNCTION zcb (K1, K2, K3) 
      INTEGER, INTENT(IN) :: K1 
      INTEGER, INTENT(IN) :: K2 
      INTEGER, INTENT(IN) :: K3 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
