*
*     ------------------------------------------------------------------
*       V I J O U T
*     ------------------------------------------------------------------
*
      SUBROUTINE VIJOUT(JA,JB)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/INFORM/IREAD,IWRITE,IOUT,ISC0,ISC1,ISC2,ISC3,JSC0,JSC(4)
      COMMON/DEBUG/IBUG1,IBUG2,IBUG3,NBUG6,NBUG7,IFULL
      COMMON/MEDEFN/IHSH,NJ(16),LJ(16),NOSH1(16),NOSH2(16),J1QN1(31,3),
     :     J1QN2(31,3),IJFUL(16)
*
*     THIS SUBROUTINE IS ENTERED ONLY IF IBUG2 IS GREATER THAN ZERO
*
* --- PRINT OUT OF QUANTUM NUMBERS AND COUPLING SCHEMES FOR EACH
*     MATRIX ELEMENT AS DEFINED BY SETUP
*
    5 FORMAT(//48H L.H.S. OF HAMILTONIAN MATRIX ELEMENT DEFINED BY)
    6 FORMAT(//48H R.H.S. OF HAMILTONIAN MATRIX ELEMENT DEFINED BY)
    7 FORMAT(9H1(CONFIG ,I2,10H/V/CONFIG ,I2,1H))
    8 FORMAT(/7H NJ,LJ ,10(I6,I3))
    9 FORMAT(/6H NOSH ,10I4)
   10 FORMAT(6H J1QN ,10(I5,2I3))
      I2HSH=2*IHSH-1
      WRITE(IWRITE,7) JA,JB
      WRITE(IWRITE,8) (NJ(I),LJ(I),I=1,IHSH)
      WRITE(IWRITE,5)
      WRITE(IWRITE,9) (NOSH1(J),J=1,IHSH)
      WRITE(IWRITE,10) ((J1QN1(J,K),K=1,3),J=1,I2HSH)
      WRITE(IWRITE,6)
      WRITE(IWRITE,9) (NOSH2(J),J=1,IHSH)
      WRITE(IWRITE,10) ((J1QN2(J,K),K=1,3),J=1,I2HSH)
    1 RETURN
      END
