      MODULE tritst_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:35:42  11/20/01  
      DOUBLE PRECISION FUNCTION tritst (L, M, N) 
      INTEGER, INTENT(IN) :: L 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(IN) :: N 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
