*
*     ------------------------------------------------------------------
*       O R T H O G G
*     ------------------------------------------------------------------
*
      SUBROUTINE ORTHOGG(LET)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/INFORM/IREAD,IWRITE,IOUT,ISC(4),IALL,JSC(3),ISCW
      COMMON/DEBUG/IBUG1,IBUG2,IBUG3,NBUG6,NBUG7,IFULL
      COMMON/MEDEFN/IHSH,NJ(16),LJ(16),NOSH1(16),NOSH2(16),J1QN1(31,3),
     :     J1QN2(31,3),IJFUL(16)
      COMMON/SIGNF /SIGNFA
*
*     THIS SUBROUTINE CHECKS FOR POSSIBLE ORTHOGONALITY DUE TO
*     COUPLING DIFFERENCES OR UNEVEN PARITY
*
  102 FORMAT(52H ORTHOGONALITY IN COUPLING SCHEMES OF CONFIGURATIONS)
  103 FORMAT(59H THE TWO CONFIGURATIONS HAVE DIFFERING NUMBERS OF ELECTR
     :ONS)
  104 FORMAT(51H THE TWO CONFIGURATIONS HAVE DIFFERING TOTAL PARITY)
*
* --- DO PSI AND PSIP CONTAIN THE SAME NUMBERS OF ELECTRONS
*     DO PSI AND PSIP HAVE THE SAME TOTAL PARITY
*
      N5=0
      N6=0
      N7=0
      DO 1 I=1,IHSH
        L1=LJ(I)
        L2=NOSH1(I)
        L3=NOSH2(I)
        N5=N5+L2
        N6=N6+L3
        N7=N7+L1*(L2-L3)
    1 CONTINUE
*
*     CHECK ON NUMBER OF ELECTRONS
*
      IF ((N5-N6).NE.0) THEN
        WRITE(IWRITE,103)
        LET=0
*
*     CHECK ON PARITY
*
      ELSE
        IF((N7-N7/2*2).NE.0) THEN
          WRITE(IWRITE,104)
          LET=0
        ELSE
          N72=N7/2
          SIGNFA=1.D0
          IF( (N72-(N72/2)*2).NE.0 ) SIGNFA=-SIGNFA
*
* --- COUPLING ORTHOGONALITY TEST FOR FIRST TWO SHELLS
*
          LET=1
        ENDIF
      ENDIF
      RETURN
      END
