*
*     ------------------------------------------------------------------
*       A C N F I G
*     ------------------------------------------------------------------
*
      SUBROUTINE ACNFIG(NCLOSD)
*
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
*
      COMMON/CONSTS/ZERO,TENTH,HALF,ONE,TWO,THREE,FOUR,SEVEN,ELEVEN,EPS
      COMMON/INFORM/IREAD,IWRITE,IOUT,ISC(8),ISCW
      POINTER(QNOC,NOCCSH(1)),(QNELCSH,NELCSH(8,1)),
     :       (QNOCORB,NOCORB(8,1)),(QJ1,J1QNRD(15,1))
      POINTER(QIAJCMP,IAJCMP(1)),(QLJCOMP,LJCOMP(1)),
     :       (QNJCOMP,NJCOMP(1)),(QIAJCLD,IAJCLD(1)),
     :       (QLJCLSD,LJCLSD(1))
      COMMON /NDIMS/ QNOC,QNELCSH,QNOCORB,QJ1,NCFG
      COMMON /NON30/ QIAJCMP,QNJCOMP,QLJCOMP,QIAJCLD,QLJCLSD,MAXORB
      POINTER(QSIGNFA,SIGNFA(1))
      COMMON/PHASES/QSIGNFA,ICSTAS
      POINTER(QACMULT,ACMULT(1))
      COMMON /SPORB/ QACMULT
*
    2 FORMAT(1H1////29X,21H---------------------/29X,21HTHE CONFIGURATIO
     :N SET/29X,21H---------------------///)
*
*     READ IN (AND PRINT OUT) CONFIGURATIONS
*
      CALL CFGO1(NCFG,MAXORB,NCLOSD,QIAJCMP,QLJCOMP,QNJCOMP,
     :                 QNOC,QNELCSH,QNOCORB,QJ1,QIAJCLD,QLJCLSD)
      call alloc(qsignfa,ncfg,8)
      call alloc(qacmult,maxorb,8)
*
*     DETERMINE THE SIGN ASSOCIATED WITH ANGULAR MOMENTUM PHASE
*          CONVENTIONS
*
   22 ISTART=1
   23 IEND=NCFG
      SIGNFA(ISTART)=ONE
      LBASE=0
      N1=NOCCSH(ISTART)
      DO 7 I=1,N1
      N2=NOCORB(I,ISTART)
      LBASE=LBASE+NELCSH(I,ISTART)*LJCOMP(N2)
    7 CONTINUE
      ISP1=ISTART+1
      DO 13 N=ISP1,IEND
      LPHASE=0
      N1=NOCCSH(N)
      DO 4 I=1,N1
      N2=NOCORB(I,N)
      LPHASE=LPHASE+NELCSH(I,N)*LJCOMP(N2)
    4 CONTINUE
      LPHASE=(LPHASE-LBASE)/2
      IF((LPHASE-LPHASE/2*2).EQ.0) GO TO 5
      SIGNFA(N)=-ONE
      GO TO 13
    5 SIGNFA(N)=ONE
   13 CONTINUE
   21 CONTINUE
      RETURN
      END
